name: CI
on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  runpypi:
    runs-on: ubuntu-latest
    environment: deploy
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
      with:
        repository: MDAnalysis/mda-xdrlib
        ref: 'v0.1.0'

    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: pypi
      uses: IAlibay/pypi-deployment@main
      with:
        token: ${{ secrets.PYPI_API_TOKEN }}
        wheels: true
        tests: true
        package_name: 'mda_xdrlib'
        continue_on_failure: true

  runtestpypi:
    runs-on: ubuntu-latest
    environment: deploy
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
      with:
        repository: MDAnalysis/mda-xdrlib
        ref: 'v0.1.0'

    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: testpypi
      uses: IAlibay/pypi-deployment@main
      with:
        token: ${{ secrets.TEST_PYPI_API_TOKEN }}
        test_submission: true
        package_name: 'mda_xdrlib'
        continue_on_failure: true

