name: CI
on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main
  schedule:
    # 3 am Tuesdays and Fridays
    - cron: "0 3 * * 2,5"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  runpypi:
    runs-on: ubuntu-latest
    environment: deploy
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
      with:
        repository: MDAnalysis/mda-xdrlib
        ref: 'v0.1.0'

    - name: pypi
      uses: IAlibay/pypi-deployment@main
      with:
        token: ${{ secrets.PYPI_API_TOKEN }}
        package_name: 'mda_xdrlib'

  runtestpypi:
    runs-on: ubuntu-latest
    environment: deploy
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
      with:
        repository: MDAnalysis/mda-xdrlib
        ref: 'v0.1.0'

    - name: testpypi
      uses: IAlibay/pypi-deployment@main
      with:
        token: ${{ secrets.TEST_PYPI_API_TOKEN }}
        test_submission: true
        tests: true
        wheels: false
        package_name: 'mda_xdrlib'

  runtestpypi_griddataformats:
    runs-on: ubuntu-latest
    environment: deploy
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
      with:
        repository: MDAnalysis/GridDataFormats
        ref: '1.0.1'

    - name: testpypi
      uses: IAlibay/pypi-deployment@main
      with:
        token: ${{ secrets.TEST_PYPI_API_TOKEN }}
        test_submission: true
        tests: true
        wheels: false
        package_name: 'griddataformats'
        module_name: 'gridData'
